// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CardCollectionController from "./card_collection_controller"
application.register("card-collection", CardCollectionController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)


import ChartController from "./chart_controller"
application.register("chart", ChartController)

import DropController from "./drop_controller"
application.register("drop", DropController)


import HelloController from "./hello_controller"
application.register("hello", HelloController)

import OngletController from "./onglet_controller"
application.register("onglet", OngletController)

import TypingController from "./typing_controller"
application.register("typing", TypingController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import CounterController from "./counter_controller"
application.register("counter", CounterController)

import MultiStepFormController from "./multi_step_form_controller"
application.register("multi-step-form", MultiStepFormController)

import CardSelectorController from "./card_selector_controller"
application.register("card-selector", CardSelectorController)
